[package]
name = "example_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.7.0"
actix-web = {version = "4", features = ["openssl"]}
aws_nitro_tls = { path = "../aws_nitro_tls" }
clap = {version = "3.2", features = ["derive"]}
env_logger = "0.7"
log = "0.4"
